CREATE DATABASE Veiculos;
GO

USE Veiculos;
GO

CREATE TABLE TipoVeiculo
(
IdTipoVeiculo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo VARCHAR(100) NOT NULL
);
GO


CREATE TABLE Veiculo
(
IdVeiculo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) NOT NULL,
Imagem VARCHAR(100),
IdTipoVeiculo UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoVeiculo(IdTipoVeiculo)
);
GO

CREATE TABLE Usuario
(
IdUsuario VARCHAR(40) PRIMARY KEY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(256) NOT NULL,
Senha VARCHAR(60) NOT NULL
);
GO

DROP TABLE Usuario